Create pt-BR translation file
archlinux/archinstall pull request #1216
Opened 2022-05-19 09:19 UTC by cain-dev

create a different file to Brazilian Portuguese

2022-05-19 09:21 UTC, Torxed commented
It would be nice with a english topic and description.
I get that this is a translation of some sort? :)

2022-05-19 12:05 UTC, svartkanin commented
@cain-dev can you please run the script again to also generate tge .mo file, otherwise the translation won't actually work.

In addition I don't know if ptbr is a valid locale abbreviation so it  might not get picked up, so would be good if you could give it a try after generating the .mo file :)

2022-05-19 12:40 UTC, Alexmelman88 commented
The correct spelling for the Brazilian locale is pt_BR, in other projects it is.

2022-05-19 18:32 UTC, Torxed commented
> > @cain-dev can you please run the script again to also generate tge .mo file, otherwise the translation won't actually work.
> > In addition I don't know if ptbr is a valid locale abbreviation so it might not get picked up, so would be good if you could give it a try after generating the .mo file :)
> 
> script? sorry, i have always changed the text of the base file to write the msgtr on nvim. What is the correct way to do this? im gonna create a corret pull request then

You might just be able to run the script with your current changes :)
It's mentioned in the locale README: https://github.com/archlinux/archinstall/blob/master/archinstall/locales/README.md

2022-05-19 18:41 UTC, cain-dev commented
i will create a temporary directory just for reference

2022-05-19 20:36 UTC, cain-dev commented
could you guys accept the pull just to have some file to someone else who wants to contribute plz?

2022-05-19 20:56 UTC, dylanmtaylor commented
> could you guys accept the pull just to have some file to someone else who wants to contribute plz? it's almost finished btw

It would be preferable to not have half done translations in the repo. My vote is to wait until it is ready

2022-05-19 20:59 UTC, cain-dev commented
> > could you guys accept the pull just to have some file to someone else who wants to contribute plz? it's almost finished btw
> 
> It would be preferable to not have half done translations in the repo. My vote is to wait until it is ready

it's not half done, it's more than 80% done, also KDE br team always come here to help translate

it's just 1 txt file, nothing more for some hours of my free work, just trying to help cause i have to rest a little

2022-05-19 21:14 UTC, Torxed commented
> > > could you guys accept the pull just to have some file to someone else who wants to contribute plz? it's almost finished btw
> > 
> > 
> > It would be preferable to not have half done translations in the repo. My vote is to wait until it is ready
> 
> it's not half done, it's more than 80% done (just me), also KDE br team always come here to help translate
> 
> it's just 1 txt file, nothing more for some hours of my free work, just trying to help cause i have to rest a little
> 
> just trying not lose my done work and not make them lose time, that's it

Understandable, ping me when you are satisfied and feel ready and I'll have a look at it :)

2022-05-19 21:27 UTC, Alexmelman88 requested changes

2022-05-19 21:27 UTC, Alexmelman88 commented on archinstall/locales/pt_BR/LC_MESSAGES/tradução.txt
> +msgstr "Selecione qual modo configurar para \"{}\" ou ignore para usar o modo padrão \"{}\"
```suggestion
msgstr "Selecione qual modo configurar para \"{}\" ou ignore para usar o modo padrão \"{}\""
```

2022-05-19 21:27 UTC, Alexmelman88 commented on archinstall/locales/pt_BR/LC_MESSAGES/tradução.txt
> +{}\n"
```suggestion
"{}\n"
```

2022-05-19 21:27 UTC, Alexmelman88 commented on archinstall/locales/pt_BR/LC_MESSAGES/tradução.txt
> +msgstr "Selecione por índice quais partições remover"
```suggestion
msgstr ""
"{}\n"
"\n"
"Selecione por índice quais partições remover"
```

2022-05-19 21:27 UTC, Alexmelman88 commented on archinstall/locales/pt_BR/LC_MESSAGES/tradução.txt
> +msgstr "Selecione por índice quais partições montar em"
```suggestion
msgstr ""
"{}\n"
"\n"
"Selecione por índice quais partições montar em"
```

2022-05-19 21:27 UTC, Alexmelman88 commented on archinstall/locales/pt_BR/LC_MESSAGES/tradução.txt
> +msgstr "Selecione qual partição mascarar para formatar"
```suggestion
msgstr ""
"{}\n"
"\n"
"Selecione qual partição mascarar para formatar"
```

2022-05-19 21:27 UTC, Alexmelman88 commented on archinstall/locales/pt_BR/LC_MESSAGES/tradução.txt
> +msgstr "Selecione qual partição marcar como encriptada"
```suggestion
msgstr ""
"{}\n"
"\n"
"Selecione qual partição marcar como encriptada"
```

2022-05-19 21:27 UTC, Alexmelman88 commented on archinstall/locales/pt_BR/LC_MESSAGES/tradução.txt
> +msgstr "Selecione qual partição marcar como bootável"
```suggestion
msgstr ""
"{}\n"
"\n"
"Selecione qual partição marcar como bootável"
```

2022-05-19 21:27 UTC, Alexmelman88 commented on archinstall/locales/pt_BR/LC_MESSAGES/tradução.txt
> +msgstr "Selecione qual partição definir um sistema de arquivos"
```suggestion
msgstr ""
"{}\n"
"\n"
"Selecione qual partição definir um sistema de arquivos"
```

2022-05-19 21:27 UTC, Alexmelman88 commented on archinstall/locales/pt_BR/LC_MESSAGES/tradução.txt
> +msgstr "Selecione o que fazer com\n"
```suggestion
msgstr "Selecione o que fazer com\n"
"{}"
```

2022-05-19 21:27 UTC, Alexmelman88 commented on archinstall/locales/pt_BR/LC_MESSAGES/tradução.txt
> +msgstr "Selecione um driver de vídeo ou deixe em branco para instalar todos os drivers open-source"
```suggestion
msgstr ""
"\n"
"\n"
"Selecione um driver de vídeo ou deixe em branco para instalar todos os drivers open-source"
```

2022-05-19 21:27 UTC, Alexmelman88 commented on archinstall/locales/pt_BR/LC_MESSAGES/tradução.txt
> +msgstr "Por favor envie este problema (e o arquivo) para https://github.com/archlinux/archinstall/issues"
```suggestion
msgstr "    Por favor envie este problema (e o arquivo) para https://github.com/archlinux/archinstall/issues"
```

2022-05-19 21:37 UTC, cain-dev commented on archinstall/locales/pt_BR/LC_MESSAGES/tradução.txt
> +msgstr "Por favor envie este problema (e o arquivo) para https://github.com/archlinux/archinstall/issues"
thank you

2022-05-19 23:10 UTC, cain-dev commented
@Torxed , everything is there, could you guys please just run the script for me and merge? thanks

2022-05-19 23:11 UTC, dylanmtaylor commented
> @Torxed , everything is there, could you guys please just run the script for me and merge? thanks

Thanks for the translation work! I'm sure someone else could run the script and make another commit, that shouldn't be an issue.

2022-05-19 23:21 UTC, svartkanin commented
It has to be someone with superpowers to commit to this PR :)

2022-05-19 23:21 UTC, cain-dev commented
the script isn't working for me, where is the pt_BR on the json file?

2022-05-20 03:45 UTC, dylanmtaylor commented
> It has to be someone with superpowers to commit to this PR :)

You can always make a merge request against his branch to add your commits.

2022-05-21 06:39 UTC, merged