Initial swapfile prototype
archlinux/archinstall pull request #1558
Opened 2022-11-12 23:29 UTC by chestwood96

Implements creating a swapfile and enabling hibernation in installer.py.

2022-11-15 20:12 UTC, Torxed requested changes

2022-11-15 20:44 UTC, chestwood96 commented on archinstall/lib/installer.py
> +		if not (SysCommand(f'dd if=/dev/zero of={self.target}{file} bs={size} count=1').exit_code == 0 and
If it throws an error by itself it actually doesn't even really need the whole if clause thing, could probably ommit that entirely then

2022-11-15 22:39 UTC, Torxed commented on archinstall/lib/installer.py
> +		if not (SysCommand(f'dd if=/dev/zero of={self.target}{file} bs={size} count=1').exit_code == 0 and
Works too, as long as the exception doesn't cause user concerns (we've had that in the past, where the argument is "why does it just crash? Can't you do nice error handling?") :P

2023-03-10 14:07 UTC, Torxed commented
Nice work, I added some additional error handling for the filename.
Other than that, looks good and merging!

2023-03-10 14:07 UTC, merged