Fix undefined variables in installer
archlinux/archinstall pull request #156
Opened 2021-04-03 21:50 UTC by rkiyanchuk

Fix few undefined variables found by static check in installer code.

I replaced undefined `log_path` with `storage['LOG_PATH']`, and further at `genfstab` step there was undefined `o` varaible in error log message: not immediately clear what it's supposed to reference, so I just removed it for now. Please let me know if the intent was to log some other variable there!

## Checklist:

- [ ] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code to the best of my abilities
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation where possible/if applicable

2021-04-04 09:45 UTC, Torxed requested changes
Looks great, if it's not to much trouble push a commit to add the debug output back which I forgot to correct way back when :)

2021-04-06 16:30 UTC, Torxed commented on archinstall/lib/installer.py
> +			raise RequirementError(f'Could not generate fstab, strapping in packages most likely failed (disk out of space?)\n')
I went ahead and added the log back :)

2021-04-06 16:31 UTC, Torxed approved these changes

2021-04-06 16:31 UTC, merged

2021-04-10 16:59 UTC, rkiyanchuk commented
My bad for the delay, was out traveling last week :) Thanks for merging anyway!

2021-04-10 21:05 UTC, Torxed commented
No worries, I realized I can commit fixes to your branch before merging hehe. So no worries :)