Added Hebrew translation.
archlinux/archinstall pull request #2348
Opened 2024-01-24 05:34 UTC by yarons

## PR Description:

Adding base.po and base.mo in Hebrew (Full translation).

## Tests and Checks
- [x] I have tested the code!<be>

Tested on a virtual machine and found several issues described in #2347, but having the complete translation will motivate fixing those :)

2024-01-24 09:29 UTC, yarons commented
There's some error regarding a missing license file. Is there anything I can do to fix it?

2024-01-24 10:07 UTC, yarons commented
I've accidentally added the README change to this branch, I'll start over if needed, sorry about that.

2024-01-25 06:27 UTC, svartkanin requested changes

2024-01-25 06:27 UTC, svartkanin commented on README.md
> -    # cd archinstall-git
Can we leave this line as it's necessary

2024-01-25 06:27 UTC, svartkanin commented
That's okay, I left a small comment

2024-01-25 21:37 UTC, svartkanin commented
Great, I don't have merging power so we have to wait for @Torxed

2024-03-07 11:57 UTC, Torxed approved these changes

2024-03-07 11:58 UTC, merged

2024-03-07 13:42 UTC, yarons commented
I've observed some issues with the Linux native console (the text is reversed), fbterm looks better but I'm looking for a better-supported console solution.