Fix most mypy errors in archinstall/scripts/, docs/, and the __init__ file
archlinux/archinstall pull request #2641
Opened 2024-08-27 16:14 UTC by correctmost

## PR Description:

This PR fixes more of the simple mypy errors in the codebase.  There are still ~150 left.

## Tests and Checks
- [ ] I have tested the code!<br>

2024-08-27 16:47 UTC, Torxed approved these changes

2024-08-28 14:12 UTC, svartkanin requested changes
Docs check is failing

2024-08-28 14:23 UTC, svartkanin commented
Hmm interesting, @Torxed any ideas? I don't think this is related to the PR in any case so we can probably merge this for now

2024-08-28 14:23 UTC, svartkanin approved these changes

2024-08-28 14:24 UTC, merged