Fixed Typo
archlinux/archinstall pull request #2765
Opened 2024-11-01 14:34 UTC by prashasth-nair

- This fix issue: 

## PR Description:

## Tests and Checks
- [ ] I have tested the code!<br>
  

Changed "Mask" to "Mark". Issue: #2762

2024-11-02 20:42 UTC, svartkanin commented
Just changing the translations will not solve this. You'll need to change it in the code where it's actually uses

2024-11-04 11:45 UTC, Torxed approved these changes

2024-11-04 11:47 UTC, Torxed requested changes
Change the `_("string")` in the code as well that uses this string.

2025-03-01 23:24 UTC, svartkanin commented
As this has been stale for quite a while I'll close this PR for now. 
If you'd like to update the PR we can revisit this in the future

2025-03-01 23:24 UTC, closed without merging