Add helpful tips for saving config files in a directory
archlinux/archinstall pull request #2803
Opened 2024-11-14 20:44 UTC by jackdesert

## PR Description

The first few times I used archinstall, I struggled with saving config files to a directory. It sounds easy, I know. But at the time I kept getting errors and finally gave up saving any config files at all. 

This PR makes it obvious why tab-completion is a boon in this scenario. It also gives a couple useful working locations, and it clarifies that extra steps are needed if you want your config files to persist through a boot cycle.

Here is a screenshot showing the updated text:
![2024-11-14 15 42 46](https://github.com/user-attachments/assets/9f3b3a8f-302a-4f5e-962e-3cdc15739343)

## Tests and Checks
- [ ] I have tested the code!<br>

2024-11-15 02:54 UTC, svartkanin requested changes

2024-11-15 02:54 UTC, svartkanin commented on archinstall/lib/configuration.py
> +Into which DIRECTORY should the configuration(s) be saved?
this is goind to output every time someone presses <tab> which is quite annoying
![image](https://github.com/user-attachments/assets/fbae2097-e775-41d8-af9d-74449b0ec859)

I would be better to show this output only once on the top

2024-11-15 09:30 UTC, Torxed commented
Maybe we could mention that the current installation is mounted under `/mnt/archinstall` as well? In case they want to save it to their recently installed system - instead of them having to manually mount something?

Or simply:

```
Do you want to save your configuration choices as a JSON file in your newly installed system?

Yes / No
```

And then put it somewhere safe?

2025-03-01 23:24 UTC, svartkanin commented
As this has been stale for quite a while I'll close this PR for now. 
If you'd like to update the PR we can revisit this in the future

2025-03-01 23:24 UTC, closed without merging