Add prompt for home partition
archlinux/archinstall pull request #801
Opened 2021-12-15 02:49 UTC by HTV04

Adds the following prompt to the archinstall setup: "Would you like to create a separate partition for /home? (Y/n): "

This allows the user to choose whether to add a separate partition for /home (current default behavior) or include it within the root partition, even if BTRFS subvolumes aren't being used or there is enough space on the disk for a separate /home partition.

2021-12-15 03:12 UTC, dylanmtaylor commented
We already have fully custom partitioning support, I'm not sure if this is that much more user-friendly.

2021-12-15 03:32 UTC, HTV04 commented
> We already have fully custom partitioning support, I'm not sure if this is that much more user-friendly.

It's a common choice to make a separate /home partition because it allows for easy persistence between Arch reinstalls, however, the same goes for those who would prefer to keep everything in one partition. Having a /home partition means that the root partition must be limited, and the script by default limits it to 20 GB, giving the rest to the /home partition.

While archinstall does support custom partition support (via scripting, iirc), having this option available from the installer would still be very useful and convenient, in my opinion.

2022-01-02 13:08 UTC, Torxed requested changes

2022-01-02 17:09 UTC, HTV04 commented on archinstall/lib/disk/user_guides.py
> +	if not using_subvolumes or block_device.size >= MIN_SIZE_TO_ALLOW_HOME_PART:
Fixed in 31a00ca

2022-01-03 11:24 UTC, Torxed commented
Thank you for those latest changes.
In recent light of all the trouble the `/home` partition has created, I think it makes sense to merge this in so that users can more safely choose whether or not they want a separate `/home` partition and judge it for themselves. Manually editing the JSON every time they want to remove/add it is a bit cumbersome and this saves some time.

2022-01-04 13:31 UTC, merged